<span id="top"></span>

<header id="masthead">
	<div class="container">
    <div class="top-band"></div>
        <section class="list header__nav">
            <ul class="list">
                <li><a class="button" href="main.php"><span>Home</span></a></li>
                <li><a class="button" href="admin.php"><span>Admin</span></a></li>
                <li><a class="button" href="index.php"><span>logout</span></a></li>
            </ul>
        </section>
	</div>
</header>