<html>

    <head>

        <title>ctba admin</title>

        <!-- Load JQuery Library -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

        <!-- Testing -->
        <link rel="stylesheet" type="text/css" href="assets/css/stylesheet.css">
        <script src="assets/js/app.js"></script>

        <!-- Live -->
        <link rel="stylesheet" type="text/css" href="assets/css/stylesheet.css">
        <script src="assets/js/app.js"></script>

    </head>